version: '3'

services:
  plant-me-api:
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: mongod --port 27017
    ports:
      - 27017:27017